const inventorySeedData = [
  {
    id: "pollo-asado",
    name: "Pollo Asado",
    unitLabel: "medios pollos",
    displayUnit: "medios",
    storedUnit: "halfUnits",
    quantity: 20,
    lowStockThreshold: 4,
    description: "Inventario para pollo asado. 1 pollo entero = 2 medios.",
    isTracked: true,
    order: 1,
  },
  {
    id: "pollo-ataud",
    name: "Pollo al Ataúd",
    unitLabel: "medios pollos",
    displayUnit: "medios",
    storedUnit: "halfUnits",
    quantity: 20,
    lowStockThreshold: 4,
    description: "Inventario para pollo al ataúd. 1 pollo entero = 2 medios.",
    isTracked: true,
    order: 2,
  },
  {
    id: "sirloin",
    name: "Sirloin",
    unitLabel: "kg",
    displayUnit: "kg",
    storedUnit: "grams",
    quantity: 10000,
    lowStockThreshold: 2000,
    description: "El admin edita en kg, pero se guarda internamente en gramos.",
    isTracked: true,
    order: 3,
  },
  {
    id: "cebolla-asada",
    name: "Cebolla Asada",
    unitLabel: "medias cebollas",
    displayUnit: "medias",
    storedUnit: "halfUnits",
    quantity: 20,
    lowStockThreshold: 6,
    description: "1 cebolla completa = 2 medias cebollas.",
    isTracked: true,
    order: 4,
  },
  {
    id: "salchicha",
    name: "Salchicha",
    unitLabel: "unidades",
    displayUnit: "unidades",
    storedUnit: "units",
    quantity: 30,
    lowStockThreshold: 8,
    description: "Salchichas disponibles para paquetes y complementos.",
    isTracked: true,
    order: 5,
  },
  {
    id: "papitas-picositas",
    name: "Papitas Picositas",
    unitLabel: "porciones",
    displayUnit: "porciones",
    storedUnit: "units",
    quantity: 25,
    lowStockThreshold: 5,
    description: "Porciones disponibles.",
    isTracked: true,
    order: 6,
  },
  {
    id: "totopos",
    name: "Totopos",
    unitLabel: "porciones",
    displayUnit: "porciones",
    storedUnit: "units",
    quantity: 25,
    lowStockThreshold: 5,
    description: "Porciones disponibles.",
    isTracked: true,
    order: 7,
  },
  {
    id: "quesadillas",
    name: "Quesadillas",
    unitLabel: "unidades",
    displayUnit: "unidades",
    storedUnit: "units",
    quantity: 40,
    lowStockThreshold: 10,
    description: "Inventario contado por unidad.",
    isTracked: true,
    order: 8,
  },
];

module.exports = inventorySeedData;