const menuSeedData = [
  {
    id: "pollo-asado",
    category: "Individuales",
    name: "1 Pollo Asado",
    price: 225,
    image: "/images/products/pollo-asado.jpg",
    description: "Pollo entero preparado al carbón.",
    badge: "Clásico",
    isAvailable: true,
    order: 1,
    inventoryUsage: [
      {
        inventoryId: "pollo-asado",
        amount: 2,
      },
    ],
  },
  {
    id: "pollo-ataud",
    category: "Individuales",
    name: "1 Pollo al Ataúd",
    price: 225,
    image: "/images/products/pollo-ataud.jpg",
    description: "Pollo entero con preparación especial al ataúd.",
    badge: "Especial",
    isAvailable: true,
    order: 2,
    inventoryUsage: [
      {
        inventoryId: "pollo-ataud",
        amount: 2,
      },
    ],
  },
  {
    id: "medio-pollo-asado",
    category: "Individuales",
    name: "1/2 Pollo Asado",
    price: 130,
    image: "/images/products/medio-pollo-asado.jpg",
    description: "Media pieza de pollo asado al carbón.",
    badge: "Pedido mínimo",
    isAvailable: true,
    order: 3,
    inventoryUsage: [
      {
        inventoryId: "pollo-asado",
        amount: 1,
      },
    ],
  },
  {
    id: "medio-pollo-ataud",
    category: "Individuales",
    name: "1/2 Pollo al Ataúd",
    price: 130,
    image: "/images/products/medio-pollo-ataud.jpg",
    description: "Media pieza de pollo al ataúd.",
    badge: "Pedido mínimo",
    isAvailable: true,
    order: 4,
    inventoryUsage: [
      {
        inventoryId: "pollo-ataud",
        amount: 1,
      },
    ],
  },
  {
    id: "sirloin-kg",
    category: "Individuales",
    name: "1 kg Sirloin",
    price: 399,
    image: "/images/products/sirloin-kg.jpg",
    description: "Sirloin preparado al carbón, ideal para compartir.",
    badge: "Al carbón",
    isAvailable: true,
    order: 5,
    inventoryUsage: [
      {
        inventoryId: "sirloin",
        amount: 1000,
      },
    ],
  },
  {
    id: "sirloin-medio-kg",
    category: "Individuales",
    name: "1/2 kg Sirloin",
    price: 219,
    image: "/images/products/sirloin-medio-kg.jpg",
    description: "Media porción de sirloin preparado al carbón.",
    badge: "Al carbón",
    isAvailable: true,
    order: 6,
    inventoryUsage: [
      {
        inventoryId: "sirloin",
        amount: 500,
      },
    ],
  },
  {
    id: "paquete-medio-asado",
    category: "Paquetes",
    name: "Paquete Medio Asado",
    price: 319,
    badge: "Para compartir",
    image: "/images/products/paquete-medio-asado.jpg",
    description:
      "1/2 pollo asado, 1/2 kg de sirloin, media cebolla asada y 1 salchicha.",
    isFeatured: true,
    isAvailable: true,
    order: 7,
    inventoryUsage: [
      { inventoryId: "pollo-asado", amount: 1 },
      { inventoryId: "sirloin", amount: 500 },
      { inventoryId: "cebolla-asada", amount: 1 },
      { inventoryId: "salchicha", amount: 1 },
    ],
  },
  {
    id: "paquete-medio-ataud",
    category: "Paquetes",
    name: "Paquete Medio Ataúd",
    price: 319,
    badge: "Sabor especial",
    image: "/images/products/paquete-medio-ataud.jpg",
    description:
      "1/2 pollo al ataúd, 1/2 kg de sirloin, media cebolla asada y 1 salchicha.",
    isFeatured: true,
    isAvailable: true,
    order: 8,
    inventoryUsage: [
      { inventoryId: "pollo-ataud", amount: 1 },
      { inventoryId: "sirloin", amount: 500 },
      { inventoryId: "cebolla-asada", amount: 1 },
      { inventoryId: "salchicha", amount: 1 },
    ],
  },
  {
    id: "paquete-familiar-asado",
    category: "Paquetes",
    name: "Paquete Familiar Asado",
    price: 589,
    badge: "Más completo",
    image: "/images/products/paquete-familiar-asado.jpg",
    description:
      "1 pollo asado, 1 kg de sirloin, 1 cebolla asada y 1 salchicha.",
    isFeatured: true,
    isAvailable: true,
    order: 9,
    inventoryUsage: [
      { inventoryId: "pollo-asado", amount: 2 },
      { inventoryId: "sirloin", amount: 1000 },
      { inventoryId: "cebolla-asada", amount: 2 },
      { inventoryId: "salchicha", amount: 1 },
    ],
  },
  {
    id: "paquete-familiar-ataud",
    category: "Paquetes",
    name: "Paquete Familiar Ataúd",
    price: 589,
    badge: "Especial familiar",
    image: "/images/products/paquete-familiar-ataud.jpg",
    description:
      "1 pollo al ataúd, 1 kg de sirloin, 1 cebolla asada y 1 salchicha.",
    isFeatured: true,
    isAvailable: true,
    order: 10,
    inventoryUsage: [
      { inventoryId: "pollo-ataud", amount: 2 },
      { inventoryId: "sirloin", amount: 1000 },
      { inventoryId: "cebolla-asada", amount: 2 },
      { inventoryId: "salchicha", amount: 1 },
    ],
  },
  {
    id: "salchicha",
    category: "Complementos",
    name: "Salchicha",
    price: 25,
    image: "/images/products/salchicha.jpg",
    description: "Salchicha asada para acompañar tu pedido.",
    badge: "Complemento",
    isAvailable: true,
    order: 11,
    inventoryUsage: [{ inventoryId: "salchicha", amount: 1 }],
  },
  {
    id: "arroz",
    category: "Complementos",
    name: "Arroz",
    price: "Desde $20",
    image: "/images/products/arroz.jpg",
    description: "Disponible en presentación chica o grande.",
    badge: "Complemento",
    isAvailable: true,
    order: 12,
    options: [
      { id: "arroz-chico", name: "Chico", price: 20 },
      { id: "arroz-grande", name: "Grande", price: 40 },
    ],
  },
  {
    id: "frijoles",
    category: "Complementos",
    name: "Frijoles",
    price: "Desde $20",
    image: "/images/products/frijoles.jpg",
    description: "Disponible en presentación chica o grande.",
    badge: "Complemento",
    isAvailable: true,
    order: 13,
    options: [
      { id: "frijoles-chicos", name: "Chicos", price: 20 },
      { id: "frijoles-grandes", name: "Grandes", price: 40 },
    ],
  },
  {
    id: "cebolla-asada",
    category: "Complementos",
    name: "Cebolla Asada",
    price: 30,
    image: "/images/products/cebolla-asada.jpg",
    description: "Cebolla asada para acompañar pollo o sirloin.",
    badge: "Complemento",
    isAvailable: true,
    order: 14,
    inventoryUsage: [{ inventoryId: "cebolla-asada", amount: 2 }],
  },
  {
    id: "papitas-picositas",
    category: "Complementos",
    name: "Papitas Picositas",
    price: 45,
    image: "/images/products/papitas-picositas.jpg",
    description: "Papitas con toque picosito.",
    badge: "Complemento",
    isAvailable: true,
    order: 15,
    inventoryUsage: [{ inventoryId: "papitas-picositas", amount: 1 }],
  },
  {
    id: "totopos",
    category: "Complementos",
    name: "Totopos",
    price: 20,
    image: "/images/products/totopos.jpg",
    description: "Totopos crujientes para acompañar.",
    badge: "Complemento",
    isAvailable: true,
    order: 16,
    inventoryUsage: [{ inventoryId: "totopos", amount: 1 }],
  },
  {
    id: "quesadilla-uno",
    category: "Complementos",
    name: "Quesadilla (1)",
    price: 15,
    image: "/images/products/quesadilla.jpg",
    description: "Una quesadilla recién hecha.",
    badge: "Complemento",
    isAvailable: true,
    order: 17,
    inventoryUsage: [{ inventoryId: "quesadillas", amount: 1 }],
  },
  {
    id: "quesadillas-cuatro",
    category: "Complementos",
    name: "Quesadillas (4)",
    price: 50,
    image: "/images/products/quesadillas-cuatro.jpg",
    description: "Orden de cuatro quesadillas.",
    badge: "Complemento",
    isAvailable: true,
    order: 18,
    inventoryUsage: [{ inventoryId: "quesadillas", amount: 4 }],
  },
  {
    id: "coca-cola",
    category: "Bebidas",
    name: "Coca Cola",
    price: 30,
    image: "/images/products/coca-cola.jpg",
    description: "Refresco para acompañar tu pedido.",
    badge: "Bebida",
    isAvailable: true,
    order: 19,
  },
  {
    id: "coke-zero",
    category: "Bebidas",
    name: "Coke Zero",
    price: 30,
    image: "/images/products/coke-zero.jpg",
    description: "Refresco sin azúcar.",
    badge: "Bebida",
    isAvailable: true,
    order: 20,
  },
  {
    id: "sprite",
    category: "Bebidas",
    name: "Sprite",
    price: 30,
    image: "/images/products/sprite.jpg",
    description: "Refresco sabor lima-limón.",
    badge: "Bebida",
    isAvailable: true,
    order: 21,
  },
  {
    id: "joya",
    category: "Bebidas",
    name: "Joya",
    price: 30,
    image: "/images/products/joya.jpg",
    description: "Refresco Joya.",
    badge: "Bebida",
    isAvailable: true,
    order: 22,
  },
  {
    id: "agua",
    category: "Bebidas",
    name: "Agua",
    price: 20,
    image: "/images/products/agua.jpg",
    description: "Agua natural para acompañar tu pedido.",
    badge: "Bebida",
    isAvailable: true,
    order: 23,
  },
  {
    id: "ensalada-cesar",
    category: "Ensaladas",
    name: "Ensalada César",
    price: 100,
    image: "/images/products/ensalada-cesar.jpg",
    description: "Ensalada César para acompañar.",
    badge: "Ensalada",
    isAvailable: true,
    order: 24,
  },
  {
    id: "carlota",
    category: "Postres",
    name: "Carlota",
    price: 40,
    image: "/images/products/carlota.jpg",
    description: "Postre frío y cremoso para cerrar tu comida.",
    badge: "Postre",
    isAvailable: true,
    order: 25,
  },
];

module.exports = menuSeedData;